sudo: required
# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - IN_TRAVIS=true

language: go
go:
  - "1.13.x"
go_import_path: github.com/maolin-sen/redis-operator

before_script:
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.6.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.6/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo helm.tgz https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz && tar -zxvf helm.tgz && sudo mv linux-amd64/helm /usr/local/bin/helm
  - mkdir -p $HOME/.kube $HOME/.minikube
  - touch $KUBECONFIG
  - helm init -c

script:
  - make test
